// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CopyOutfit(arg1:string):Promise<void>;

export function FollowOff():Promise<void>;

export function FollowOn():Promise<void>;

export function FollowUser(arg1:string):Promise<void>;

export function LoadAndApplyOutfit(arg1:string):Promise<void>;

export function LoadConfig():Promise<main.OutfitConfig>;

export function LoadOutfit(arg1:string):Promise<main.OutfitDetails>;

export function LoadUsers():Promise<Array<string>>;

export function MimicOff():Promise<void>;

export function MimicOn():Promise<void>;

export function SaveConfig(arg1:main.OutfitConfig):Promise<void>;

export function SaveOutfit(arg1:string,arg2:string):Promise<void>;

export function SaveOutfitFromUsername(arg1:string,arg2:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function StopFollowingUser(arg1:string):Promise<void>;
