// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyOutfit(arg1) {
  return window['go']['main']['App']['CopyOutfit'](arg1);
}

export function FollowOff() {
  return window['go']['main']['App']['FollowOff']();
}

export function FollowOn() {
  return window['go']['main']['App']['FollowOn']();
}

export function FollowUser(arg1) {
  return window['go']['main']['App']['FollowUser'](arg1);
}

export function LoadAndApplyOutfit(arg1) {
  return window['go']['main']['App']['LoadAndApplyOutfit'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadOutfit(arg1) {
  return window['go']['main']['App']['LoadOutfit'](arg1);
}

export function LoadUsers() {
  return window['go']['main']['App']['LoadUsers']();
}

export function MimicOff() {
  return window['go']['main']['App']['MimicOff']();
}

export function MimicOn() {
  return window['go']['main']['App']['MimicOn']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveOutfit(arg1, arg2) {
  return window['go']['main']['App']['SaveOutfit'](arg1, arg2);
}

export function SaveOutfitFromUsername(arg1, arg2) {
  return window['go']['main']['App']['SaveOutfitFromUsername'](arg1, arg2);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StopFollowingUser(arg1) {
  return window['go']['main']['App']['StopFollowingUser'](arg1);
}
